version: '3'

services:
  sonar:
    image: sonarqube:alpine
    ports:
      - 9001:9000
      - 9092:9092
    depends_on:
      - sonar-db
    environment:
      - SONARQUBE_JDBC_USERNAME=sonar
      - SONARQUBE_JDBC_PASSWORD=sonar
      - SONARQUBE_JDBC_URL=jdbc:postgresql://sonar-db/sonar

  sonar-db:
    image: postgres:10-alpine
    environment:
      - POSTGRES_PASSWORD=sonar
      - POSTGRES_USER=sonar
      - POSTGRES_DB=sonar

